app_info:
    name: github.com/godverv/Velez
    version: v0.1.43
    startup_duration: 10s
servers:
    53890:
        /{GRPC}:
            module: pkg/velez_api
            gateway: /api
environment:
    - name: available ports
      type: int
      value:
        - 18501
        - 18502
        - 18503
        - 18504
        - 18505
        - 18506
        - 18507
        - 18508
        - 18509
        - 18510
        - 18511
        - 18512
        - 18513
        - 18514
        - 18515
        - 18516
        - 18517
        - 18518
        - 18519
    - name: cpu default
      type: float
      value: 0.5
    - name: custom pass to key
      type: string
      value: /tmp/velez/private.key
    - name: disable api security
      type: bool
      value: false
    - name: expose matreshka port
      type: bool
      value: true
    - name: makosh expose port
      type: bool
      value: true
    - name: makosh image name
      type: string
      value: godverv/makosh:v0.0.3
    - name: makosh key
      type: string
      value: string
    - name: makosh port
      type: int
      value: 50051
    - name: makosh url
      type: string
      value: verv://makosh
    - name: matreshka port
      type: int
      value: 50050
    - name: matreshka url
      type: string
      value: verv://matreshka
    - name: memory swap mb
      type: int
      value: 50
    - name: node mode
      type: bool
      value: true
    - name: portainer enabled
      type: bool
      value: false
    - name: ram mb default
      type: int
      value: 50
    - name: shut down on exit
      type: bool
      value: false
    - name: watch tower enabled
      type: bool
      value: true
    - name: watch tower interval
      type: duration
      value: 1m0s
