app_info:
  name: github.com/godverv/Velez
  version: v0.1.30
  startup_duration: 10s
data_sources:
  - resource_name: grpc_matreshka_be
    connection_string: matreshka:80
    module: github.com/godverv/matreshka-be@v1.0.23
server:
  - name: grpc
    port: 80
environment:
  available_ports:
    - 18501-18519

  custom_pass_to_key: /tmp/velez/private.key

  disable_api_security: false

  cpu_default: 0.5
  memory_swap_mb: 50
  ram_mb_default: 50

  node_mode: true
  expose_matreshka_port: true
  matreshka_port: 50050

  portainer_enabled: false
  shut_down_on_exit: false

  watch_tower_enabled: true
  watch_tower_interval: 5s
