app_info:
    name: github.com/godverv/Velez
    version: 0.0.1
    startup_duration: 10s
data_sources: []
server:
    - name: grpc
      port: 50051
      gateway_port: 0
environment:
    available_ports:
        - 18501-18519
    cpu_default: 0.5
    memory_swap_mb: 50
    portainer_enabled: true
    ram_mb_default: 50
    watch_tower_enabled: true
    watch_tower_interval: 5s
