app_info:
  name: github.com/godverv/Velez
  version: v0.1.41
  startup_duration: 10s
data_sources:
  - resource_name: grpc_matreshka_be
    connection_string: matreshka:50050
    module: github.com/godverv/matreshka-be@v1.0.23
server:
  - name: grpc
    port: 53890
environment:
  - name: available_ports
    value: 18501-18519
    type: int

  - name: custom_pass_to_key
    value: /tmp/velez/private.key
    type: string

  - name: disable_api_security
    value: false
    type: bool

  - name: cpu_default
    value: 0.5
    type: float
  - name: memory_swap_mb
    value: 50
    type: int
  - name: ram_mb_default
    value: 50
    type: int

  - name: node_mode
    value: true
    type: bool

  - name: expose_matreshka_port
    value: true
    type: bool
  - name: matreshka_port
    value: 50050
    type: int

  - name: portainer_enabled
    value: false
    type: bool

  - name: shut_down_on_exit
    value: true
    type: bool


  - name: watch_tower_enabled
    value: true
    type: bool
  - name: watch_tower_interval
    value: 5s
    type: duration
