app_info:
    name: github.com/godverv/Velez
    version: 0.0.1
    startup_duration: 10s
data_sources: []
server:
    - name: grpc
      port: 50051
environment:
    available_ports:
        - 18501-18519
