app_info:
    name: github.com/godverv/Velez
    version: v0.0.1
    startup_duration: 10s
data_sources: []
server:
    - name: grpc
      port: 50051
environment:
  cpu_default: 0.5
  ram_mb_default: 50
  memory_swap_mb: 50
