app_info:
  name: github.com/godverv/Velez
  version: v0.1.43
  startup_duration: 10s
data_sources: []
servers:
  53890:
    /{GRPC}:
      module: pkg/velez_api
      gateway: /api
environment:
  #  Node settings
  - name: node mode
    value: true
    type: bool
  - name: available ports
    value: 18501-18519
    type: int
  - name: shut down on exit
    value: false
    type: bool

  # Security
  - name: custom pass to key
    value: /tmp/velez/private.key
    type: string
  - name: disable api security
    value: false
    type: bool

  # Hardware default settings
  - name: cpu default
    value: 0.5
    type: float
  - name: memory swap mb
    value: 50
    type: int
  - name: ram mb default
    value: 50
    type: int

  # Matreshka
  - name: expose matreshka port
    value: true
    type: bool
  - name: matreshka port
    value: 50050
    type: int
  # Makosh settings
  - name: makosh expose port
    value: true
    type: bool
  - name: makosh port
    value: 50051
    type: int
  - name: makosh image name
    type: string
    value: godverv/makosh:v0.0.3
  - name: makosh key
    value: string
    type: string

  # Portainer
  - name: portainer enabled
    value: false
    type: bool

  # Watchtower
  - name: watch tower enabled
    value: true
    type: bool
  - name: watch tower interval
    value: 60s
    type: duration

  # Service discovery
  - name: makosh_url
    type: string
    value: verv://makosh

  # Configuration service
  - name: matreshka_url
    type: string
    value: verv://matreshka
