app_info:
  name: github.com/godverv/Velez
  version: v0.1.43
  startup_duration: 10s
data_sources: []
servers:
  53890:
    /{GRPC}:
      module: pkg/velez_api
      gateway: /api
environment:
  - name: available ports
    type: int
    value: 18501-18519
  - name: cpu default
    type: float
    value: 0.5
  - name: custom pass to key
    type: string
    value: /tmp/velez/private.key
  - name: disable api security
    type: bool
    value: false
  - name: expose matreshka port
    type: bool
    value: true
  - name: makosh expose port
    type: bool
    value: true
  - name: makosh image name
    type: string
    value: godverv/makosh:v0.0.3
  - name: makosh key
    type: string
    value: string
  - name: makosh port
    type: int
    value: 50051
  - name: matreshka port
    type: int
    value: 50050
  - name: memory swap mb
    type: int
    value: 50
  - name: node mode
    type: bool
    value: true
  - name: portainer enabled
    type: bool
    value: false
  - name: ram mb default
    type: int
    value: 50
  - name: shut down on exit
    type: bool
    value: false
  - name: watch tower enabled
    type: bool
    value: true
  - name: watch tower interval
    type: duration
    value: 1m0s

  # Service discovery
  - name: makosh_urls
    type: string
    value: [verv://makosh]

  # Configuration service
  - name: makosh_urls
    type: string
    value: [verv://matreshka]
