app_info:
    name: github.com/godverv/Velez
    version: v0.1.43
    startup_duration: 10s
data_sources:
    - resource_name: grpc_matreshka_be
      connection_string: matreshka
      module: github.com/godverv/matreshka-be@v1.0.31
    - resource_name: grpc_makosh
      connection_string: makosh
      module: github.com/godverv/makosh@v0.0.1
server:
    - name: grpc
      port: 53890
environment:
    - name: available ports
      type: int
      value:
        - 18501
        - 18502
        - 18503
        - 18504
        - 18505
        - 18506
        - 18507
        - 18508
        - 18509
        - 18510
        - 18511
        - 18512
        - 18513
        - 18514
        - 18515
        - 18516
        - 18517
        - 18518
        - 18519
    - name: cpu default
      type: float
      value: 0.5
    - name: custom pass to key
      type: string
      value: /tmp/velez/private.key
    - name: disable api security
      type: bool
      value: false
    - name: expose matreshka port
      type: bool
      value: true
    - name: makosh expose port
      type: bool
      value: true
    - name: makosh image name
      type: string
      value: godverv/makosh:v0.0.1
    - name: makosh port
      type: int
      value: 50051
    - name: matreshka port
      type: int
      value: 50050
    - name: memory swap mb
      type: int
      value: 50
    - name: node mode
      type: bool
      value: true
    - name: portainer enabled
      type: bool
      value: false
    - name: ram mb default
      type: int
      value: 50
    - name: shut down on exit
      type: bool
      value: false
    - name: watch tower enabled
      type: bool
      value: true
    - name: watch tower interval
      type: duration
      value: 1m0s
