app_info:
    name: github.com/godverv/Velez
    version: 0.0.1
    startup_duration: 10s
data_sources:
    - resource_name: grpc_matreshka_be
      connection_string: localhost:50050
      module: github.com/godverv/matreshka-be@v1.0.23
server:
    - name: grpc
      port: 50051
      gateway_port: 0
environment:
    available_ports:
        - 18501-18519
    cpu_default: 0.5
    disable_api_security: true
    memory_swap_mb: 50
    portainer_enabled: true
    ram_mb_default: 50
    shut_down_on_exit: true
    watch_tower_enabled: true
    watch_tower_interval: 5s
    expose_matreshka_port: true
    node_mode: true