name: branch-push
run-name: ${{ github.REF_NAME }} pull request
on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  create-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Create PR
        uses: RedSockActions/create_pr@v0.0.10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    runs-on: ubuntu-24.04
    needs:
      - create-pr
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: docker build -t velez:${{ github.sha }} .

      - name: Run container
        run: |
          docker run --name e2e-velez -p 53890:53890 -v /var/run/docker.sock:/var/run/docker.sock -e DISABLE_API_SECURITY=true velez:${{ github.sha }} 
          sleep 2
        continue-on-error: false

      - name: Test
        run: go test -tags github_wf ./...