name: branch-push
run-name: ${{ github.REF_NAME }} pull request
on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  create-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Create PR
        uses: RedSockActions/create_pr@v0.0.10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: docker build -t velez:integration-tests .

      -   name: Run container
          run: |
            docker run -d --name velez -p 53890:53890 -v /var/run/docker.sock:/var/run/docker.sock -v ./tests/config/config.yaml:/app/config/config.yaml velez:integration-tests
            sleep 5

      - name: Test
        run: go test -tags="rscliErrorTracingEnabled integration github_wf" ./... | grep -v 'no test files'

      -   name: Stop container
          run: |
            docker rm -f velez