name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release
        uses: RedSockActions/release_tag@v1.1.0
        with:
          token: ${{ github.token }}
    outputs:
      tag: ${{ steps.release.outputs.tag }}

  registry_release:
    runs-on: ubuntu-latest
    needs:
      - tag-release
    steps:
      - name: Release
        if: ${{ needs.tag-release.outputs.tag }} != ""
        uses: RedSockActions/release_image@1a3c00f3b5ae9ae115580600a9b9196b3fa3ff5a
        with:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PWD:  ${{ secrets.REGISTRY_PWD }}