name: master-actions
run-name: RELEASE
on:
    push:
        branches:
            - "master"

jobs:
    tag-release:
        runs-on: ubuntu-latest
        steps:
            -   name: Release tag
                id: release
                uses: RedSockActions/release_tag@v1.1.6
                with:
                    token: ${{ github.token }}
        outputs:
            tag: ${{ steps.release.outputs.tag }}

    registry_release:
        runs-on: ubuntu-latest
        needs:
            - tag-release
        steps:
            -   name: Release image
                if: ${{ needs.tag-release.outputs.tag != '' }}
                uses: RedSockActions/release_image@v1.0.19
                with:
                    REGISTRY_USER: ${{ vars.REGISTRY_USER }}
                    REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}

    publish-npm:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 20
                    registry-url: https://registry.npmjs.org/

            -   name: Install dependencies
                working-directory: pkg/web
                run: yarn install

            -   name: Build
                working-directory: pkg/web
                run: yarn build

            -   name: Publish to npm
                working-directory: pkg/web
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                    PACKAGE_TAG: "v0.1.46"
                run: |
                    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
                    yarn publish --non-interactive --access public --tag $PACKAGE_TAG
