name: Publish docker image
on:
  push:
    tags:
      - '*'
jobs:
  registry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Define owner name
        uses: ASzc/change-string-case-action@v5
        id: owner_name
        with:
          string: ${{ github.repository_owner }}

      - name: Define repo name
        uses: ASzc/change-string-case-action@v5
        id: repo_name
        with:
          string: ${{ github.event.repository.name }}

      - name: Set output
        id: tag_short
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Define version tag
        uses: ASzc/change-string-case-action@v5
        id: tag
        with:
          string: ${{ steps.tag_short.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}

      - name: Build and push image
        run: |
          docker build -t ${{ steps.owner_name.outputs.lowercase }}/${{ steps.repo_name.outputs.lowercase }}:${{ steps.tag.outputs.lowercase }} -t ${{ steps.owner_name.outputs.lowercase }}/${{ steps.repo_name.outputs.lowercase }}:latest .
          docker push ${{ steps.owner_name.outputs.lowercase }}/${{ steps.repo_name.outputs.lowercase }}:${{ steps.tag.outputs.lowercase }}
          docker push ${{ steps.owner_name.outputs.lowercase }}/${{ steps.repo_name.outputs.lowercase }}:latest
 
