name: Publish docker image
on:
  release:
    types: [created]

jobs:
  registry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: RedSockActions/release_image@v0.0.2

