name: Publish docker image
on:
  push:
    tags:
      - '*'
jobs:
  registry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Alya pushing
        run: |
          echo '${{ github.event.repository.name }}'
          echo '${{ github.ref }}'
      #      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          platforms: linux/amd64,linux/arm64
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest

#      - name: Build and push image
#        run: |
#          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PWD }} ${{ secrets.REGISTRY_HOST }}
#          docker build -t ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}:$GITHUB_REF_TYPE -t ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}:latest .
#          docker push ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}:$GITHUB_REF_TYPE
#          docker push ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}:latest
 
